### ISSUE TITLE
Sprint 40, GitHub action - 3 tests failed - 007 Nifi+LDIO, 013 due to default configuration of gtfs2ldes-js

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#397]
GitHub action result: https://github.com/xdxxxdx/VSDS-LDES-E2E-testing/actions/runs/6967548568/job/18961230745
--
With tags for Sprint 39: 
[VSDS-LDESServer4J](https://hub.docker.com/r/ldes/ldes-server/tags) 

- tag: [ldes/ldes-server: 2.4.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldes-server/tags) 

[VSDS-Linked-Data-Interactions](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions)

- [ldi-workbench-nifi](https://hub.docker.com/r/ldes/ldi-workbench-nifi/tags) tag: [ldes/ldi-workbench-nifi:1.10.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldi-workbench-nifi/tags)

- [ldi-orchestrator](https://hub.docker.com/r/ldes/ldi-orchestrator/tags) tag: [ldes/ldi-orchestrator:1.10.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldi-orchestrator/tags)

---
The 3 failing actions are due to the default configuration of  gtfs2ldes-js
![image](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/assets/15314807/9ee7db2b-b200-422b-9875-0f327a44db4b)

https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/tests/007.server-ingest-large-ldes/docker-compose.yml

GTFS_SOURCE:-https://www.rtd-denver.com/files/gtfs/bustang-co-us.zip etc..

![image](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/assets/15314807/e4135a70-aff9-47cc-96ba-27a6d7a76a6f)
---
Logs:

```
2023-11-23 11:51:00 /******************************************/
2023-11-23 11:51:00 Starting processing of GTFS source
2023-11-23 11:51:01 Downloading https://www.rtd-denver.com/files/gtfs/bustang-co-us.zip ...
2023-11-23 11:51:01 Decompressing GTFS source...
2023-11-23 11:51:01 Error: invalid signature: 0x4f44213c
2023-11-23 11:51:01     at /opt/gtfs2ldes/node_modules/unzipper/lib/parse.js:70:26
2023-11-23 11:51:01     at tryCatcher (/opt/gtfs2ldes/node_modules/bluebird/js/release/util.js:16:23)
2023-11-23 11:51:01     at Promise._settlePromiseFromHandler (/opt/gtfs2ldes/node_modules/bluebird/js/release/promise.js:510:31)
2023-11-23 11:51:01     at Promise._settlePromise (/opt/gtfs2ldes/node_modules/bluebird/js/release/promise.js:567:18)
2023-11-23 11:51:01     at Promise._settlePromise0 (/opt/gtfs2ldes/node_modules/bluebird/js/release/promise.js:612:10)
2023-11-23 11:51:01     at Promise._settlePromises (/opt/gtfs2ldes/node_modules/bluebird/js/release/promise.js:691:18)
2023-11-23 11:51:01     at Async._drainQueue (/opt/gtfs2ldes/node_modules/bluebird/js/release/async.js:133:16)
2023-11-23 11:51:01     at Async._drainQueues (/opt/gtfs2ldes/node_modules/bluebird/js/release/async.js:143:10)
2023-11-23 11:51:01     at Async.drainQueues (/opt/gtfs2ldes/node_modules/bluebird/js/release/async.js:17:14)
2023-11-23 11:51:01     at process.processImmediate (node:internal/timers:476:21)
2023-11-23 11:51:01 node:internal/process/promises:288
2023-11-23 11:51:01             triggerUncaughtException(err, true /* fromPromise */);
2023-11-23 11:51:01             ^
2023-11-23 11:51:01 
2023-11-23 11:51:01 Error: invalid signature: 0x4f44213c
2023-11-23 11:51:01     at /opt/gtfs2ldes/node_modules/unzipper/lib/parse.js:70:26
2023-11-23 11:51:01     at tryCatcher (/opt/gtfs2ldes/node_modules/bluebird/js/release/util.js:16:23)
2023-11-23 11:51:01     at Promise._settlePromiseFromHandler (/opt/gtfs2ldes/node_modules/bluebird/js/release/promise.js:510:31)
2023-11-23 11:51:01     at Promise._settlePromise (/opt/gtfs2ldes/node_modules/bluebird/js/release/promise.js:567:18)
2023-11-23 11:51:01     at Promise._settlePromise0 (/opt/gtfs2ldes/node_modules/bluebird/js/release/promise.js:612:10)
2023-11-23 11:51:01     at Promise._settlePromises (/opt/gtfs2ldes/node_modules/bluebird/js/release/promise.js:691:18)
2023-11-23 11:51:01     at Async._drainQueue (/opt/gtfs2ldes/node_modules/bluebird/js/release/async.js:133:16)
2023-11-23 11:51:01     at Async._drainQueues (/opt/gtfs2ldes/node_modules/bluebird/js/release/async.js:143:10)
2023-11-23 11:51:01     at Async.drainQueues (/opt/gtfs2ldes/node_modules/bluebird/js/release/async.js:17:14)
2023-11-23 11:51:01     at process.processImmediate (node:internal/timers:476:21)
2023-11-23 11:51:01 
2023-11-23 11:51:01 Node.js v18.15.0
```

**Comment by rorlic** [comment]
Hi, there is indeed something wrong with the gtfs2ldes image. I noticed this too. Julian has made some fixes on December 20th but unfortunately these introduced a different issue. I made him aware of that.

As the gtfs2ldes-js image is not under our control I have disabled tests 007 and 013 until a fix is available [here](https://github.com/julianrojas87/gtfs2ldes-js/pkgs/container/gtfs2ldes-js).

**Comment by rorlic** [comment]
It turned out to be our mistake: due to the multi-typed server change we could not determine the actual member if multiple named nodes were in the ingested member message. This is now fixed by using the isVersionOf to determine the member id.
